// render/mesh_gpu.c (skeleton -- shows the shape peranti_draw_frame will
// take once world_storage and the greedy-mesh pipeline exist)

#include "mesh_gpu.h"

#include <string.h>

// Generated by build-zig.sh's build_shaders() step from
// shaders/terrain.glsl. Must be regenerated (and this file recompiled)
// whenever terrain.glsl changes.
#include "../generated/terrain.glsl.h"

#ifdef __cplusplus
extern "C" {
#endif

// Set up once, not per-frame -- called from renderingengine.cpp right
// after sg_setup() (and its GL-state save/restore bracket). Owns the
// vertex-pulling shader/pipeline, since a pipeline is a fixed GPU object,
// not something rebuilt every draw.
static sg_pipeline g_terrain_pipeline;

uint32_t pack_quad_word0(uint32_t x, uint32_t y, uint32_t z, uint32_t width, uint32_t height, uint32_t axis, uint32_t direction) {
  // Apply width-1 and height-1 adjustments as noted in layout
    uint32_t w_minus_1 = width - 1;
    uint32_t h_minus_1 = height - 1;

    // Mask each value to ensure it strictly respects its bit-budget
    uint32_t masked_x    = x           & 0x1FU; // 5 bits (0-31)
    uint32_t masked_y    = y           & 0x1FU; // 5 bits (0-31)
    uint32_t masked_z    = z           & 0x1FU; // 5 bits (0-31)
    uint32_t masked_w    = w_minus_1   & 0x1FU; // 5 bits (0-31)
    uint32_t masked_h    = h_minus_1   & 0x1FU; // 5 bits (0-31)
    uint32_t masked_axis = axis        & 0x03U; // 2 bits (0-3)
    uint32_t masked_dir  = direction   & 0x01U; // 1 bit  (0-1)

    // Combine them by shifting each into its designated bit slot
    uint32_t word0 = (masked_x    << 0)  |
                     (masked_y    << 5)  |
                     (masked_z    << 10) |
                     (masked_w    << 15) |
                     (masked_h    << 20) |
                     (masked_axis << 25) |
                     (masked_dir  << 27);

    return word0;
}

void peranti_render_init(void) {
  // Generated by build-zig.sh's build_shaders() step from
  // shaders/terrain.glsl -- the function name (terrain_shader_desc) comes
  // from the shader's @program name.
  sg_shader shd = sg_make_shader(terrain_shader_desc(sg_query_backend()));

  sg_pipeline_desc pip_desc;
  memset(&pip_desc, 0, sizeof(pip_desc)); // memset, not = {0} -- see
                                            // CONVENTIONS.md rule 8
  pip_desc.shader = shd;
  pip_desc.depth.compare = SG_COMPAREFUNC_LESS_EQUAL;
  pip_desc.depth.write_enabled = true;
  // No vertex layout to declare at all -- vertex pulling means there are
  // no bound vertex buffers or attributes for this pipeline, everything
  // comes from the storage buffer read in the shader via gl_InstanceIndex.
  // face_winding left at its default (SG_FACEWINDING_CW) -- matches
  // Irrlicht's glFrontFace(GL_CW), confirmed earlier, no override needed.
  g_terrain_pipeline = sg_make_pipeline(&pip_desc);
}

void peranti_draw_frame(void) {
  // The GL framebuffer id for onscreen rendering is 0 -- confirmed back
  // when sg_environment/sg_swapchain were first investigated. No
  // sglue_swapchain() helper exists here since sokol_app isn't in the
  // picture; this is the manual equivalent, built by hand every frame.
  sg_pass_action pass_action;
  // memset, not = {0}: sg_pass_action's own first field (colors[0].load_action)
  // is itself an enum with no leading canary/int field to absorb the
  // literal 0 safely -- unlike sg_desc/sg_pass, which start with a plain
  // uint32_t _start_canary and are fine with = {0}. memset is a byte-level
  // operation, not a typed aggregate initializer, so it sidesteps the
  // C++ int-to-enum restriction entirely. See CONVENTIONS.md.
  memset(&pass_action, 0, sizeof(pass_action));
  // {0}/memset-zero resolves to _SG_LOADACTION_DEFAULT, which the sokol
  // docs confirm means SG_LOADACTION_CLEAR -- the opposite of what's
  // needed here, so both fields below are set explicitly regardless.
  pass_action.colors[0].load_action = SG_LOADACTION_LOAD; // Irrlicht already
                                                            // cleared via
                                                            // beginScene()
  pass_action.depth.load_action = SG_LOADACTION_LOAD;      // same buffer,
                                                            // don't re-clear

  sg_pass pass = {0};
  pass.action = pass_action;
  pass.swapchain.width = 0;  // TODO: real framebuffer width, from Irrlicht's
                              // driver->getScreenSize() via peranti_camera_sync
                              // or a dedicated viewport-sync call
  pass.swapchain.height = 0; // TODO: same, height
  pass.swapchain.sample_count = 1; // TODO: should match fsaa value used in
                                     // sg_setup()'s desc.environment.defaults
  pass.swapchain.color_format = SG_PIXELFORMAT_RGBA8;
  pass.swapchain.depth_format = SG_PIXELFORMAT_DEPTH_STENCIL;
  pass.swapchain.gl.framebuffer = 0;

  sg_begin_pass(&pass);
  sg_apply_pipeline(g_terrain_pipeline);

  // View-projection matrix built from whatever peranti_camera_sync last
  // stored -- core/projection.c's job, not this file's. Passed as a
  // uniform, shared across every chunk drawn this frame.
  // TODO: float view_proj[16]; peranti_camera_get_view_proj(view_proj);
  // sg_range vp_range = { view_proj, sizeof(view_proj) };
  // sg_apply_uniforms(0, &vp_range);

  // TODO once world_storage exists: iterate every occupied WorldChunkEntry,
  // for each one:
  //   - skip if outside frustum (naive distance check for now; the
  //     compute-shader culling from Phase D replaces this later, doesn't
  //     block getting something on screen first)
  //   - bind that chunk's packed quad storage buffer:
  //       sg_bindings bind = {0};
  //       bind.storage_buffers[0] = mesh_gpu_lookup(entry->render_handle);
  //       sg_apply_bindings(&bind);
  //   - per-chunk world-position uniform, matching the exact formula
  //     confirmed against clientmap.cpp: (block_pos * MAP_BLOCKSIZE -
  //     camera_offset) * BS -- this is core/projection.c's or this
  //     function's job to compute per chunk, not skipped.
  //   - sg_draw(0, 6, quad_count) -- 6 vertices per quad (2 triangles),
  //     instanced once per quad via vertex pulling, no traditional vertex
  //     buffer involved at all.

  sg_end_pass();
  sg_commit();
}

#ifdef __cplusplus
}
#endif
